name: greendrop
description: "A delivery app for weed products"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.20.0
  geocode: ^1.0.3
  shared_preferences: ^2.3.2
  flutter_map: ^7.0.2
  geocoding: ^2.0.5
  geolocator: ^13.0.2
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - .env
    - assets/images/shop1.jpg
    - assets/images/logo.png
    - assets/images/logo_old.png
    - assets/data/mock-shops.json
    - assets/data/mock_account.json

  uses-material-design: true