version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: greendrop_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./02_seed_data.sql:/docker-entrypoint-initdb.d/02_seed_data.sql

volumes:
  postgres_data:
