// Mocks generated by Mockito 5.4.5 from annotations
// in greendrop/test/presentation/products/provider/product_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:greendrop/src/data/repositories/interfaces/shop_repository.dart'
    as _i2;
import 'package:greendrop/src/domain/models/product.dart' as _i5;
import 'package:greendrop/src/domain/models/shop.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IShopRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIShopRepository extends _i1.Mock implements _i2.IShopRepository {
  MockIShopRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Shop>> getAllShops() =>
      (super.noSuchMethod(
            Invocation.method(#getAllShops, []),
            returnValue: _i3.Future<List<_i4.Shop>>.value(<_i4.Shop>[]),
          )
          as _i3.Future<List<_i4.Shop>>);

  @override
  _i3.Future<List<_i5.Product>> getAllShopProducts(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAllShopProducts, [id]),
            returnValue: _i3.Future<List<_i5.Product>>.value(<_i5.Product>[]),
          )
          as _i3.Future<List<_i5.Product>>);
}
